spring:
  application:
    name: ms_administrator
  webflux:
    base-path: /admin
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /v3/api-docs
    disable-swagger-default-url: true

logging:
  level:
    io.r2dbc.postgresql: DEBUG  # Para ver queries en dev