spring.application.name=ms_administrator

server.port=8081

# Habilitar actuator en el Gateway
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# Ruta para health del Gateway
spring.cloud.gateway.discovery.locator.enabled=true

# ===========================
# Swagger / OpenAPI (WebFlux)
# ===========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
# Opcional: forzar URL de docs si el redirect falla
springdoc.swagger-ui.url=/v3/api-docs
# Mostrar también en la UI de Swagger la base-path
springdoc.swagger-ui.disable-swagger-default-url=true

# PostgreSQL R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/restaurant_admin
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# JPA (solo para migraciones si las usas)
# spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_admin
# spring.datasource.username=postgres
# spring.datasource.password=postgres

# Reactive WebFlux
spring.webflux.base-path=/api
