# ===========================
# Configuración base
# ===========================
spring.application.name=ms_administrator
server.port=8081

# ===========================
# WebFlux
# ===========================
spring.webflux.base-path=/api

# ===========================
# PostgreSQL R2DBC
# ===========================
# spring.r2dbc.url=r2dbc:postgresql://dpg-d6h6p8ea2pns738bqo10-a.oregon-postgres.render.com:5432/app001mt_restaurante_club_comercio?sslMode=require
# spring.r2dbc.username=userquemona01
# spring.r2dbc.password=EgPkC34fFZM0ksw8FQzJeJ3fkVxXOeiK
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=require
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

# JPA (solo para migraciones si las usas)
# spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_admin
# spring.datasource.username=postgres
# spring.datasource.password=postgres

# ===========================
# Cloud Gateway
# ===========================
spring.cloud.gateway.discovery.locator.enabled=true

# ===========================
# Actuator
# ===========================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# ===========================
# Swagger / OpenAPI (WebFlux)
# ===========================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
# Opcional: forzar URL de docs si el redirect falla
springdoc.swagger-ui.url=/v3/api-docs
# Mostrar también en la UI de Swagger la base-path
springdoc.swagger-ui.disable-swagger-default-url=true