spring.application.name=ms_orders
server.port=8082

# PostgreSQL R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/restaurant_admin
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

# JPA (solo para migraciones si las usas)
# spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_admin
# spring.datasource.username=postgres
# spring.datasource.password=postgres

# Reactive WebFlux
spring.webflux.base-path=/api

